# Generated by Django 6.0 on 2026-01-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='origin',
            field=models.CharField(choices=[('EUR', 'Europea'), ('LAT', 'Latina'), ('BRA', 'Brasileña'), ('ASI', 'Asiatica'), ('RUS', 'Rusa/Slavic'), ('OTRO', 'Otro')], default='EUR', max_length=20, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zone',
            field=models.CharField(choices=[('EIVISSA', 'Eivissa'), ('SANT_ANTONI', 'Sant Antoni de Portmany'), ('SANTA_EULARIA', 'Santa Eulalia'), ('SANT_JOSEP', 'Sant Josep de sa Talaia'), ('SANT_JOAN', 'Sant Joan de Labritja')], default='EIVISSA', max_length=50),
        ),
    ]
