# Generated by Django 6.0 on 2026-01-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_origin_alter_profile_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_visits',
            field=models.PositiveIntegerField(default=0, verbose_name='Visitas al Perfil'),
        ),
    ]
