# Generated by Django 6.0 on 2026-01-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_age_profile_avatar_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_email', models.EmailField(default='soporte@ahhh-ibiza.com', help_text='Correo de soporte para usuarios', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Activar modo mantenimiento')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
    ]
