# Generated by Django 6.0 on 2026-01-06 20:32

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profilemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profilemedia',
            name='file',
            field=models.FileField(upload_to=apps.accounts.models.user_directory_path),
        ),
    ]
