# Generated by Django 6.0 on 2026-06-20 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_avatar_alter_profilemedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='trash_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trashed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilemedia',
            name='trash_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profilemedia',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilemedia',
            name='trashed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_profile_media', to=settings.AUTH_USER_MODEL),
        ),
    ]
