# Generated by Django 6.0 on 2026-06-20 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_trash_note_customuser_trashed_at_and_more'),
        ('ads', '0007_seed_promotion_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='ads.ad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anuncio favorito',
                'verbose_name_plural': 'Anuncios favoritos',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'ad')},
            },
        ),
    ]
