# Generated by Django 6.0.7 on 2026-08-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('CLIENT', 'Cliente'), ('PROFESSIONAL', 'Profesional')], db_index=True, default='CLIENT', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
