# Generated by Django 6.0.7 on 2026-08-12 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TangasPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('tangas_amount', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Tangas')),
                ('price_eur', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Precio (EUR)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paquete de Tangas',
                'verbose_name_plural': 'Paquetes de Tangas',
                'ordering': ['sort_order', 'price_eur', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(max_length=50, verbose_name='Pasarela')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Carga útil')),
                ('status', models.CharField(default='received', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de webhook',
                'verbose_name_plural': 'Registros de webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tangas_amount', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Tangas')),
                ('amount_eur', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Importe (EUR)')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagada'), ('FAILED', 'Fallida'), ('CANCELLED', 'Cancelada'), ('REFUNDED', 'Reembolsada')], db_index=True, default='PENDING', max_length=20, verbose_name='Estado')),
                ('gateway', models.CharField(default='dummy', max_length=50, verbose_name='Pasarela')),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Referencia externa')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagada en')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_orders', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.tangaspackage', verbose_name='Paquete')),
            ],
            options={
                'verbose_name': 'Orden de recarga',
                'verbose_name_plural': 'Ordenes de recarga',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='recharge_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.rechargeorder', verbose_name='Orden de recarga'),
        ),
    ]
