# Generated by Django 6.0 on 2026-01-04 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('public_description', models.TextField(verbose_name='Descripción Pública')),
                ('private_description', models.TextField(blank=True, null=True, verbose_name='Descripción Privada (+18)')),
                ('price_tangas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio en Tangas')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('PAUSED', 'Pausado'), ('BANNED', 'Baneado')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ads/gallery/')),
                ('is_private', models.BooleanField(default=False, help_text='Visible solo para usuarios registrados (+18)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='ads.ad')),
            ],
        ),
    ]
