# Generated by Django 6.0 on 2026-01-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='private_description',
        ),
        migrations.AddField(
            model_name='ad',
            name='hot_description',
            field=models.TextField(blank=True, help_text='Descripción Privada HOT', null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price_tangas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='public_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo (Consume Tangas)'), ('CERRADO', 'Cerrado (Pausado)')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
