# Generated by Django 6.0 on 2026-01-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_remove_ad_private_description_ad_hot_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='hot_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Privada HOT'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='public_description',
            field=models.TextField(blank=True, verbose_name='Descripción Pública'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo (Consume Tangas)'), ('CERRADO', 'Cerrado (Sin Consumo)')], default='ACTIVE', max_length=20, verbose_name='Estado del Anuncio'),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(upload_to='ad_images/'),
        ),
        migrations.AlterField(
            model_name='adimage',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Es HOT (Privada)'),
        ),
    ]
