# Generated by Django 6.0 on 2026-01-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_hot_description_alter_ad_public_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='ads', to='ads.servicetag', verbose_name='Servicios Ofrecidos'),
        ),
    ]
