# Generated by Django 6.0 on 2026-06-20 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_servicetag_ad_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='trash_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ad',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='trashed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adimage',
            name='trash_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adimage',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adimage',
            name='trashed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_ad_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
