# Generated by Django 6.0 on 2026-06-20 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_trash_note_ad_trashed_at_ad_trashed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price_tangas', models.PositiveIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('BASIC', 'Basico'), ('FEATURED', 'Destacado'), ('TOP', 'Siempre arriba')], default='BASIC', max_length=20)),
                ('priority_weight', models.PositiveIntegerField(default=0, help_text='Mas alto aparece antes.')),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority_weight', 'price_tangas', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='promotion_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='ads.promotionproduct'),
        ),
    ]
