# Generated by Django 6.0.7 on 2026-08-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_seed_promotion_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo (Consume Tangas)'), ('CERRADO', 'Cerrado (Sin Consumo)')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Estado del Anuncio'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
