# Generated by Django 6.0.7 on 2026-08-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ad_status_alter_ad_trashed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='last_tangas_charged_at',
            field=models.DateField(blank=True, help_text='Fecha del ultimo descuento diario del plan (para no cobrar dos veces el mismo dia).', null=True, verbose_name='Último cargo de Tangas'),
        ),
    ]
