# Generated by Django 6.0.7 on 2026-08-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_ad_last_tangas_charged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='tangas_charge_exempt',
            field=models.BooleanField(default=False, help_text='Solo superadmin: el anuncio no paga Tangas aunque tenga plan de pago.', verbose_name='Exento de cobro de Tangas'),
        ),
        migrations.AddField(
            model_name='ad',
            name='tangas_exempt_reason',
            field=models.CharField(blank=True, help_text='Motivo opcional de la exencion de cobro de Tangas.', max_length=255, verbose_name='Motivo de la exención'),
        ),
    ]
